import assert from "node:assert/strict";
import test from "node:test";
import type { ParsedDocument } from "../domain/document";
import type { Source } from "../domain/source";
import { buildFileEvidence } from "../lib/research/claim-builder";
import { reconcileEvidenceConflicts } from "../lib/research/conflict-detector";
import { collectCitations } from "../lib/research/openai-research-provider";
import { verifyClaims } from "../lib/research/source-verifier";
import { buildStoryboard } from "../lib/storyboard/storyboard-builder";

const document: ParsedDocument = { fileId: "file-1", fileName: "sample.pptx", mimeType: "application/pptx", title: "能源资料", text: "容量达到 80 MW", sections: [{ id: "slide-2", section: "第 2 页", pageOrSlide: 2, text: "示范容量达到 80 MW。" }], warnings: [], metadata: { format: "pptx" } };
const brief = { topic: "校园光伏课程汇报", deckType: "课程报告", audience: "老师与同学", purpose: "解释项目", pageRange: "10", needsRecentResearch: true, uploadedFileIds: ["file-1"] };

test("file source and claim preserve page provenance", () => { const evidence = buildFileEvidence([document]); assert.equal(evidence.sources[0].sourceType, "FILE"); assert.equal(evidence.sources[0].pageOrSlide, 2); assert.deepEqual(evidence.claims[0].sourceIds, [evidence.sources[0].id]); });
test("web source provenance remains linked", () => { const source: Source = { id: "web-1", title: "Official data", url: "https://example.gov/data", publisher: "Government", retrievedAt: new Date().toISOString(), sourceType: "WEB" }; const [claim] = verifyClaims([{ id: "web-claim", text: "公开统计为 120 MW", type: "NUMERIC", numericValues: [{ value: 120, unit: "MW" }], sourceIds: [source.id], confidence: .9, needsReview: false }], [source]); assert.deepEqual(claim.sourceIds, [source.id]); assert.equal(claim.needsReview, false); });
test("mixed file and web evidence reach one storyboard", () => { const fileEvidence = buildFileEvidence([document]); const web: Source = { id: "web-1", title: "Official update", url: "https://example.gov/update", publisher: "Government", retrievedAt: new Date().toISOString(), sourceType: "WEB" }; const claims = [...fileEvidence.claims, { id: "web-claim", text: "最新政策支持校园分布式项目。", type: "FACT" as const, sourceIds: [web.id], confidence: .9, needsReview: false }]; const sources = [...fileEvidence.sources, web]; const storyboard = buildStoryboard(brief, claims, sources); const refs = new Set(storyboard.slides.flatMap(slide => slide.sourceRefs)); assert.ok(refs.has(fileEvidence.sources[0].id)); assert.ok(refs.has(web.id)); });
test("conflicting numbers are preserved without averaging", () => { const result = reconcileEvidenceConflicts([{ id: "a", claimTopic: "market-size", text: "市场规模 120", type: "NUMERIC", numericValues: [{ value: 120 }], sourceIds: ["s1"], confidence: .9, needsReview: false }, { id: "b", claimTopic: "market-size", text: "市场规模 145", type: "NUMERIC", numericValues: [{ value: 145 }], sourceIds: ["s2"], confidence: .9, needsReview: false }]); assert.equal(result.conflicts.length, 1); assert.deepEqual(result.conflicts[0].values.map(item => item.value), [120, 145]); assert.ok(result.claims.every(claim => claim.needsReview)); });
test("evidence roles carry sources or review marker", () => { const fileEvidence = buildFileEvidence([document]); const storyboard = buildStoryboard(brief, fileEvidence.claims, fileEvidence.sources); for (const slide of storyboard.slides.filter(item => ["DATA", "TREND", "MAP", "COMPARISON"].includes(item.role))) assert.ok(slide.sourceRefs.length > 0 || slide.needsReview); });
test("only tool citation annotations become web citations", () => { const citations = collectCitations([{ type: "message", content: [{ type: "output_text", text: "普通文本 https://not-a-citation.example", annotations: [{ type: "url_citation", url: "https://official.example/source", title: "Official source" }] }] }]); assert.equal(citations.size, 1); assert.equal(citations.get("https://official.example/source"), "Official source"); assert.equal(citations.has("https://not-a-citation.example"), false); });
